name: Selenium UI Automation CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BROWSER: chrome

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install latest Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v1
      with:
        chromedriver-version: latest

    - name: Run Selenium Tests
      run: |
        echo "Running Maven tests on headless Chrome"
        mvn clean test \
          -Dbrowser=${BROWSER} \
          -Dchrome.options="--headless --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-user-data-${GITHUB_RUN_ID}" \
          -Dsurefire.printSummary=true
