name: Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 4. Set up Chrome
      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      # 5. Set up ChromeDriver
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: latest

      # 6. Run Maven tests
      - name: Run Selenium Tests
        run: |
          echo "Running Maven tests on headless Chrome"
          mvn clean test \
            -Dbrowser=chrome \
            -Dchrome.options="--headless --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-user-data-${GITHUB_RUN_ID}" \
            -Dsurefire.printSummary=true
