name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Install Chrome
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      # 4. Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 5. Run Selenium tests with Maven
      - name: Run Selenium tests
        run: mvn clean test -Dbrowser=chrome -Dapp.url=https://custom-juice-shop.onrender.com/ -Denv=render
